resources:

  - name: A_Pipeinfo_gitRepo_v1
    type: GitRepo
    configuration:
      path: Varsha-Arun/Org_test_Automation
      branches:
        include: master
      gitProvider: varsha_github

  - name: A_stepArtifact_propertyBag_v1
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1

pipelines:
  - name: longLogsPipeline
    steps:

      - name: long_logs
        type: Bash
        execution:
          onExecute:
            - printenv
            - wget https://norvig.com/big.txt
            - cat big.txt  >> bigger_file.txt
            - cat big.txt >> bigger_file.txt
            - cat bigger_file.txt

          
  - name: RunHooksPipelineWithLogsAndTests
    configuration:
      environmentVariables:
        readOnly:
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    preRun:
      execution:
        onExecute:
          - printenv
          - echo "Executing Pre Run"
          - echo "new"
          - set_run_name 'pre run name'
          - update_run_description 'pre run desc'
            
    postRun:
      execution:
        onExecute:
          - printenv
          - echo "Executing Pre Run"
          - echo "new"
          - set_run_name 'post run name'
          - update_run_description 'test post run desc'

    steps:
      - name: s_stepTestReports_v1
        type: Bash
        configuration:
          environmentVariables:
            key1: "value1"
            key2: "value2"
            key3: "value3"
          inputResources:
            - name: A_Pipeinfo_gitRepo_v1
        execution:
          onExecute:
            - cd $res_A_Pipeinfo_gitRepo_v1_resourcePath
            - add_run_files tests/core/sampleExecutionFile/calc.py my_files 
            - add_run_variables JFROG_PIPELINES_RUN_STATE_DEBUG=true
            - python3 -m py_compile tests/core/sampleExecutionFile/calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest
            - cd $res_A_Pipeinfo_gitRepo_v1_resourcePath
            - py.test --verbose --junit-xml test-reports/results.xml tests/core/sampleExecutionFile/test_calc.py
            - save_tests $res_A_Pipeinfo_gitRepo_v1_resourcePath/test-reports/results.xml
            - restore_run_files my_files tests/core/sampleExecutionFile/calc.py
            - add_run_variables JFROG_PIPELINES_RUN_STATE_DEBUG=true
            
      - name: s_stepArtifacts_001_v1
        type: Bash
        configuration:
          inputResources:
            - name: A_Pipeinfo_gitRepo_v1
          integrations:
            - name: varsha_github
        execution:
          onExecute:
            - echo "executing step api_pipeinfo_step1"
          onComplete:
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_jatin_gitrepo2_commitSha
            - add_run_variables JFROG_PIPELINES_RUN_STATE_DEBUG=true
            
      - name: s_stepArtifacts_002_v1
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: s_stepArtifacts_001_v1
        stepletMultipliers:
          environmentVariables:
            - animal:    dog
              mineral:   copper
              vegetable: carrot
            - animal:    goat
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard
              mineral:   lead
        execution:
          onExecute:
            - echo "I am executing matrix steplet \${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"
            - add_run_variables JFROG_PIPELINES_RUN_STATE_DEBUG=true
      - name: s_stepArtifacts_003_v1
        type: Bash
        configuration:
          inputSteps:
            - name: s_stepArtifacts_002_v1
          outputResources:
            - name: A_stepArtifact_propertyBag_v1
        execution:
          onExecute:
#             - set_run_name 'testRunName'
#             - update_run_description 'testRunDescription'
            - echo $current_runid
            - add_pipeline_variables prev_runid=$run_id
            - add_run_variables step_one_id=\${step_id} step_one_stepletId=\${steplet_id} JFROG_PIPELINES_RUN_STATE_DEBUG=true
            - write_output resource_A_stepArtifact_propertyBag_v1 commitSha=$commitSha runID=$current_runid
            - add_run_variables JFROG_PIPELINES_RUN_STATE_DEBUG=true
